"""{{APP_NAME}} — generated by Forge.

This file is generated from a Forge manifest. Do not edit by hand —
re-run the generator with an updated manifest instead.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

DATA_DIR = Path(__file__).parent / "data"

app = FastAPI(
    title="{{APP_NAME}}",
    description="Generated analytics application for {{COMPANY}}",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def _load_json(name: str):
    path = DATA_DIR / name
    if not path.exists():
        return []
    return json.loads(path.read_text())


KPIS = _load_json("kpis.json")
AUDIENCES = _load_json("audiences.json")
DATASOURCES = _load_json("datasources.json")


@app.get("/health")
def health():
    return {"status": "ok", "app": "{{APP_SLUG}}", "company": "{{COMPANY}}"}


@app.get("/api/kpis")
def list_kpis():
    return KPIS


@app.get("/api/audiences")
def list_audiences():
    return AUDIENCES


@app.get("/api/datasources")
def list_datasources():
    # never expose secrets — only the safe metadata
    return [
        {k: v for k, v in ds.items() if k not in ("secret_ref",)}
        for ds in DATASOURCES
    ]


class AskRequest(BaseModel):
    question: str
    role_id: str = "viewer"
    user_id: str = "anonymous"


@app.post("/api/ask")
def ask(req: AskRequest):
    """NL query endpoint. In a fully-built deployment this delegates to
    forge.intelligence.executor; for the generated localhost demo we return
    a stub answer so the UI can be exercised end-to-end."""
    # Look up KPI by simple heuristic — real version uses semantic catalog
    matched = None
    q = req.question.lower()
    for k in KPIS:
        if k["name"].lower() in q:
            matched = k
            break
    if not matched and KPIS:
        matched = KPIS[0]
    if not matched:
        return {"answer": "No KPIs configured yet for this app.", "citations": []}

    return {
        "answer": (
            f"For '{matched['name']}': in a fully-wired deployment this answer would "
            f"be computed from {matched['formula']} against your live data sources. "
            f"On the demo path, your manifest configured {len(KPIS)} KPIs and "
            f"{len(DATASOURCES)} sources."
        ),
        "kpi_id": matched["id"],
        "citations": [{"source": ds["name"], "kind": ds["kind"]} for ds in DATASOURCES[:3]],
    }


@app.get("/api/insights/digest")
def digest():
    """Returns the latest proactive digest. Stub for the generated app —
    in production this is populated by the scheduled forge.insights worker."""
    return {
        "headline": f"Welcome to {{APP_NAME}}",
        "sections": [
            {"title": "Getting started",
             "bullets": [
                 f"Your manifest configured {len(KPIS)} KPIs",
                 f"You have {len(DATASOURCES)} data sources to wire",
                 "Run docker-compose up --build to start everything",
             ]}
        ],
        "anomalies": [],
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", 8000)))
