"""{{APP_NAME}} — generated by Forge.

This file is generated from a Forge manifest. Do not edit by hand —
re-run the generator with an updated manifest instead.
"""
from __future__ import annotations

import csv
import hashlib
import io
import json
import os
from pathlib import Path

from fastapi import FastAPI, File, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from fabric import fabric

DATA_DIR = Path(__file__).parent / "data"
UPLOAD_DIR = DATA_DIR / "uploads"

# Upload limits / accepted formats for the "bring your own data" feature.
MAX_UPLOAD_BYTES = 10 * 1024 * 1024  # 10 MB
PREVIEW_ROWS = 25
ALLOWED_UPLOAD_EXT = {".xlsx", ".csv"}
_last_upload: dict = {}  # in-memory cache of the most recently parsed upload

app = FastAPI(
    title="{{APP_NAME}}",
    description="Generated analytics application for {{COMPANY}}",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def _load_json(name: str):
    path = DATA_DIR / name
    if not path.exists():
        return []
    return json.loads(path.read_text())


KPIS = _load_json("kpis.json")
AUDIENCES = _load_json("audiences.json")
DATASOURCES = _load_json("datasources.json")


@app.get("/health")
def health():
    return {"status": "ok", "app": "{{APP_SLUG}}", "company": "{{COMPANY}}"}


@app.get("/api/kpis")
def list_kpis():
    return KPIS


_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def _kpi_by_id(kpi_id: str):
    for k in KPIS:
        if k.get("id") == kpi_id:
            return k
    return None


def _demo_series(kpi_id: str, points: int = 12):
    """Deterministic pseudo time-series so a KPI detail screen has a chart
    even on the demo path (no live warehouse). Same KPI → same series."""
    seed = int(hashlib.sha256(kpi_id.encode()).hexdigest()[:12], 16)
    state = seed
    def rnd():
        nonlocal state
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        return state / 0x7FFFFFFF
    value = 40 + (seed % 400)
    volatility = 0.04 + (seed % 12) / 100.0
    out = []
    for i in range(points):
        value = max(1.0, value * (1 + (rnd() - 0.42) * volatility))
        out.append({"t": _MONTHS[i % 12], "v": round(value, 2)})
    return out


@app.get("/api/kpis/{kpi_id}")
def kpi_detail(kpi_id: str):
    """Full detail for a single KPI: definition + a demo trend series and the
    current value / period-over-period delta, for the drill-down screen."""
    k = _kpi_by_id(kpi_id)
    if not k:
        raise HTTPException(404, "KPI not found")
    series = _demo_series(kpi_id)
    current = series[-1]["v"]
    previous = series[-2]["v"] if len(series) > 1 else current
    delta_pct = ((current - previous) / previous * 100.0) if previous else 0.0
    return {
        "kpi": k,
        "series": series,
        "current": current,
        "previous": previous,
        "delta_pct": round(delta_pct, 2),
        "is_demo": True,
    }


@app.get("/api/audiences")
def list_audiences():
    return AUDIENCES


@app.get("/api/datasources")
def list_datasources():
    # never expose secrets — only the safe metadata
    return [
        {k: v for k, v in ds.items() if k not in ("secret_ref",)}
        for ds in DATASOURCES
    ]


class AskRequest(BaseModel):
    question: str
    role_id: str = "viewer"
    user_id: str = "anonymous"


@app.post("/api/ask")
def ask(req: AskRequest):
    """NL query endpoint. The agent routes the question to the right data
    connection (see connections.json) and runs the matching query."""
    return fabric.ask(req.question)


# ── Data fabric: multi-source connections the agent routes across ────

class ConnectionPayload(BaseModel):
    id: str
    label: str | None = None
    engine: str
    host: str
    port: int | None = None
    database: str
    user: str
    password: str | None = None
    password_env: str | None = None
    catalog: str | None = None
    keywords: list[str] = []
    enabled: bool = True


@app.get("/api/fabric/sources")
def fabric_sources():
    return {"sources": fabric.list_sources()}


@app.get("/api/connections")
def list_connections():
    return {"connections": fabric.list_connections()}


@app.post("/api/connections")
def upsert_connection(body: ConnectionPayload):
    try:
        return fabric.upsert_connection(body.model_dump(exclude_none=True))
    except ValueError as e:
        raise HTTPException(400, str(e))


@app.post("/api/connections/test")
def test_connection(body: ConnectionPayload):
    return fabric.test_connection(body.model_dump(exclude_none=True))


@app.delete("/api/connections/{cid}")
def delete_connection(cid: str):
    return fabric.delete_connection(cid)


@app.get("/api/insights/digest")
def digest():
    """Returns the latest proactive digest. Stub for the generated app —
    in production this is populated by the scheduled forge.insights worker."""
    return {
        "headline": f"Welcome to {{APP_NAME}}",
        "sections": [
            {"title": "Getting started",
             "bullets": [
                 f"Your manifest configured {len(KPIS)} KPIs",
                 f"You have {len(DATASOURCES)} data sources to wire",
                 "Run docker-compose up --build to start everything",
             ]}
        ],
        "anomalies": [],
    }


# ── Bring your own data: Excel / CSV upload ──────────────────────────

def _safe_name(name: str) -> str:
    base = os.path.basename(name or "upload")
    cleaned = "".join(c for c in base if c.isalnum() or c in (".", "_", "-"))
    return cleaned or "upload"


def _parse_csv(raw: bytes):
    text = raw.decode("utf-8-sig", errors="replace")
    rows = list(csv.reader(io.StringIO(text)))
    if not rows:
        return [], []
    return [str(h) for h in rows[0]], rows[1:]


def _parse_xlsx(raw: bytes):
    from openpyxl import load_workbook
    wb = load_workbook(io.BytesIO(raw), read_only=True, data_only=True)
    try:
        ws = wb.active
        rows = [["" if c is None else c for c in row]
                for row in ws.iter_rows(values_only=True)]
    finally:
        wb.close()
    if not rows:
        return [], []
    return [str(h) for h in rows[0]], rows[1:]


def _numeric_summary(header, data_rows):
    """Per-column min/max/avg/sum so the UI can show instant analytics."""
    summaries = []
    for ci, col in enumerate(header):
        nums = []
        for r in data_rows:
            if ci < len(r):
                try:
                    nums.append(float(r[ci]))
                except (TypeError, ValueError):
                    pass
        # treat a column as numeric only if most of its cells parse as numbers
        if nums and len(nums) >= max(1, len(data_rows) // 2):
            summaries.append({
                "column": col, "count": len(nums),
                "min": min(nums), "max": max(nums),
                "sum": sum(nums), "avg": sum(nums) / len(nums),
            })
    return summaries


@app.post("/api/upload")
async def upload_data(file: UploadFile = File(...)):
    """Accept an Excel (.xlsx) or CSV file, parse it, and return a preview
    plus a quick numeric summary. The file is stored under data/uploads/."""
    name = _safe_name(file.filename)
    ext = os.path.splitext(name)[1].lower()
    if ext not in ALLOWED_UPLOAD_EXT:
        raise HTTPException(400, f"Unsupported file type '{ext or '?'}'. Upload .xlsx or .csv")

    raw = await file.read()
    if not raw:
        raise HTTPException(400, "Empty file")
    if len(raw) > MAX_UPLOAD_BYTES:
        raise HTTPException(413, "File too large (max 10 MB)")

    try:
        header, data_rows = _parse_xlsx(raw) if ext == ".xlsx" else _parse_csv(raw)
    except Exception as e:  # noqa: BLE001 — surface a clean client error
        raise HTTPException(422, f"Could not parse file: {e}")

    if not header:
        raise HTTPException(422, "No columns found — is the first row a header?")

    UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
    (UPLOAD_DIR / name).write_bytes(raw)

    preview = [[("" if v is None else str(v)) for v in r] for r in data_rows[:PREVIEW_ROWS]]
    result = {
        "filename": name,
        "columns": header,
        "column_count": len(header),
        "row_count": len(data_rows),
        "preview_rows": preview,
        "numeric_summary": _numeric_summary(header, data_rows),
    }
    _last_upload.clear()
    _last_upload.update(result)
    return result


@app.get("/api/uploads/latest")
def latest_upload():
    """The most recently uploaded dataset (metadata + preview), if any."""
    return _last_upload or {"filename": None, "row_count": 0, "columns": []}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", 8000)))
