# Generated by Forge for {{COMPANY}} ({{APP_SLUG}})
# Deployment target: {{DEPLOYMENT}}
#
# This is a skeleton. To apply, set the appropriate provider credentials
# and run `terraform init && terraform plan`. The localhost demo path
# stops at `terraform plan` — actual provisioning requires real cloud
# credentials configured by the customer.

terraform {
  required_version = ">= 1.5.0"
}

variable "app_slug" {
  type    = string
  default = "{{APP_SLUG}}"
}

variable "region" {
  type    = string
  default = "{{REGION}}"
}

# ── Outputs that the CI/CD pipeline can consume ─────────────────────
output "app_slug" {
  value = var.app_slug
}

output "deployment_target" {
  value = "{{DEPLOYMENT}}"
}
